#!/bin/sh

set -e

if [ -e /usr/lib/libqvimeo.so ]
    then
        rm /usr/lib/libqvimeo.so
fi

if [ -e /usr/lib/libqvimeo.so.1 ]
    then
        rm /usr/lib/libqvimeo.so.1
fi

if [ -e /usr/lib/libqvimeo.so.1.0 ]
    then
        rm /usr/lib/libqvimeo.so.1.0
fi

if [ -e /usr/lib/libqvimeo.so.1.0.0 ]
    then
        rm /usr/lib/libqvimeo.so.1.0.0
fi

if [ -h /usr/lib/qt4/imports/QVimeo ]
    then
        rm /usr/lib/qt4/imports/QVimeo
fi

exit 0
