#!/bin/sh

set -e

if [ ! -e /usr/lib/libqvimeo.so.1.0.0 ]
    then
        ln -s /opt/lib/libqvimeo.so.1.0.0 /usr/lib/libqvimeo.so.1.0.0
        ln -s /usr/lib/libqvimeo.so.1.0.0 /usr/lib/libqvimeo.so
        ln -s /usr/lib/libqvimeo.so.1.0.0 /usr/lib/libqvimeo.so.1
        ln -s /usr/lib/libqvimeo.so.1.0.0 /usr/lib/libqvimeo.so.1.0
fi

if [ ! -e  /usr/lib/qt4/imports/QVimeo ]
    then
        ln -s /opt/lib/qt4/imports/QVimeo/ /usr/lib/qt4/imports/
fi

exit 0